name: Run Python Script Daily

on:
  schedule:
    # Run the script daily at 4 AM UTC (1 AM São Paulo time - 01:00)
    - cron: "*/5 * * * *"

jobs:
  run_script:
    runs-on: windows-latest # Necessário para rodar xlwings com suporte ao Excel

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Add environment variables
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_FILE_ID: ${{ secrets.AZURE_FILE_ID }}
          AZURE_FILE_PATH: ${{ secrets.AZURE_FILE_PATH }}
          AZURE_SITE_URL: ${{ secrets.AZURE_SITE_URL }}
          EXCEL_FILE_PASSWORD: ${{ secrets.EXCEL_FILE_PASSWORD }}
          CATACLIENTE_EMAIL: ${{ secrets.CATACLIENTE_EMAIL }}
          CATACLIENTE_PASSWORD: ${{ secrets.CATACLIENTE_PASSWORD }}
        run: |
          python main.py > scrapper.log 2>&1

      # Commit the updated scrapper.log file back to the repository
      - name: Commit and push updated scrapper.log
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add scrapper.log
          git commit -m "Update scrapper.log"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Built-in secret

      - name: Upload scrapper.log as artifact
        uses: actions/upload-artifact@v3
        with:
          name: scrapper-log
          path: scrapper.log
